name: Build fixtures .ics

on:
  schedule:
    - cron: "7 */12 * * *"   # twice daily; adjust as you like
  workflow_dispatch: {}       # manual run button

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dateutil pytz flask

      - name: Build ICS
        run: |
          python scripts/fixtures_calendar.py --out docs/players-fixtures.ics

      - name: Commit if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add docs/players-fixtures.ics
            git commit -m "Update fixtures .ics"
            git push
          else
            echo "No changes."
          fi
